### DISCUSSION TITLE
disable shideshow

### DISCUSSION THREAD

**Discussion by zonky2** [biati-digital/glightbox#401] [Q&A] [answered]
Is it possible to display the lightbox without navigation for several images/content - i.e. that only one slide is displayed at a time?

**Comment by gingerchew** [comment, marked as answer]
With a small amount of JS and some CSS it's easy to add, but there is already this rule in the css.
```css
.glightbox-button-hidden {
    display: none;
}
```

You can also add an attribute to the container and make it more dynamic.
```css
[data-slides="1"] .gbtn {
    display: none;
}
```

```js
lightbox.on('open', () => {
    const container = document.querySelector('.glightbox-container');
    container.dataset.slides = container.querySelectorAll('.gslide').length;
});
```
