### ISSUE TITLE
Option to disable zoom feature

### ISSUE THREAD

**Issue by Hirbod** [biati-digital/glightbox#141]
Would be lovely to have a option disabling the zoom feature. I currently did it with CSS

```css
  img.zoomable {
    cursor: auto;
    pointer-events: none;
  }
```

which is a bit hacky to me
