### ISSUE TITLE
Youtube video - can "copy link" or browse more videos

### ISSUE THREAD

**Issue by vyskoczilova** [biati-digital/glightbox#214]
**Describe the bug**
Youtube embed in popup - copy the link or browsing more videos doesn't work.

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**
1. Go to https://biati-digital.github.io/glightbox/ and "Videos gallery" section
2. Click on the second image
3. See the error

**Expected behavior**
I would like to be able to interact with the video.

**Screenshots**
![screenshot-biati-digital github io-2021 03 15-10_19_51](https://user-images.githubusercontent.com/3611726/111131264-5dba6b00-8578-11eb-86c7-7d0802e23484.png)

**Comment by frankie-tech** [comment]
This is an issue with the styles and HTML that plyr.js adds to the page. There is a poster that it adds by default that blocks those controls.

But the solution is just one line of CSS:

```css
.gvideo-wrapper .plyr__poster-enabled.plyr--paused {
	z-index: -1;
}
```

Since those controls only show up when the video is paused, you only need to hide the poster when it is paused. Prevents any sort of weirdness when actually using the poster feature.

Hope this helps! 😊

**Comment by vyskoczilova** [comment]
@frankie-tech Thanks for a reply, but two things:

1. when I apply your CSS video gets paused and covers with black and I can't play it any longer
2. you should be able to click to "copy link" any time

Thanks for your help!

**Comment by frankie-tech** [comment]
That's because I missed a class in my selector 🙂 it should've been:

```css
.gvideo-wrapper .plyr__poster-enabled.plyr--paused .plyr__poster {
	z-index: -1;
}
```

As for number 2: you might be able to change the CSS selector to this:

```css
.gvideo-wrapper .plyr__poster-enabled .plyr__poster {
	z-index: -1;
}
```
