### ISSUE TITLE
Firefox 88 z-index hot patch

### ISSUE THREAD

**Issue by frankie-tech** [biati-digital/glightbox#241]
In Firefox 88, certain values for z-index can be converted into a hex code.

If you experience this issue while using GLightbox, you can add a number to the end of the z-index value. For example:

```css
/* may be turned into a hex code */
.glightbox-container {
    z-index: 999999 !important;
}

/* adding a 7th 9 fixes this */
.glightbox-container {
    z-index: 9999999 !important;
}
```
