### ISSUE TITLE
can not select text

### ISSUE THREAD

**Issue by viliusle** [biati-digital/glightbox#253]
**Describe the bug**
It is impossible to select text on modal inline dialog. I understand that it was disabled to be able to swipe for next modal dialog? But let's say these is only 1 dialog or using mouse (not tablet) or using draggable: false settings - in cases user should be able to select text.

p.s. possible quick fix  - edit library CSS file, .find glightbox-container .gslide selector and remove user-select lines.

**Are you able to reproduce the bug in the demo site**
Yes.

**To Reproduce**
1. Go to 'https://biati-digital.github.io/glightbox/'
2. Click on first image on "Iframes and Inline Elements" section
3. Try to select text

**Expected behavior**
You should be able to select text

**Desktop:**
 - Browser [chrome]

**Comment by frankie-tech** [comment]
Hey @viliusle,

I'm not sure this is a big enough issue to add it to the library. As you pointed out, it is really easy to fix using your own CSS.

For others who may want to turn this CSS off, all you would need to add is:

```css
.glightbox-container .gslide,
.gslide-image img {
	-webkit-user-select: auto;
	-moz-user-select: auto;
	-ms-user-select: auto;
	user-select: auto;
}
```

If you're looking to add the styles dynamically, I recommend checking out the `open` event. Then you will be able to add a class dynamically that will achieve the same outcome.

For now though, since this is easy enough to fix on your own, I'm going to close this issue.
