### ISSUE TITLE
The description box doesn't expand to the full width when the image is not preloaded

### ISSUE THREAD

**Issue by inacho** [biati-digital/glightbox#291]
**Describe the bug**
The description box doesn't expand to the full width when changing the slide and the image is not preloaded yet.
This issue happens a lot when you flick through photos in a gallery with images that have good quality (as they take longer time to completely load).

**Are you able to reproduce the bug in the demo site**
Yes

**To Reproduce**

In order to reproduce the bug easier, use a browser with an inspector that allows to throttle the network speed. For instance Firefox.

1. Open a gallery with Firefox
2. Open the inspector and go to the "network" tab
3. Activate network throttling (for example "Regular 2G")
4. Open one slide, then change to other slides quickly

**Expected behavior**
The description should expand to the same width of the image instead of being tiny

**Screenshots**

![Screen Shot 2021-09-26 at 12 31 21](https://user-images.githubusercontent.com/742624/134792796-d4b1067b-9fbf-4960-8a31-967f783eca0c.png)

**Video**

https://user-images.githubusercontent.com/742624/134792895-660c5270-6db3-4cec-93ba-2dcd478cdaa6.mov

**Comment by inacho** [comment]
Hey,

I'm using the following workaround:

Basically moving the div.gslide-description inside .gslide-media instead of having it as a sibling, so when .gslide-media expands, the description will expand as well.

Javascript:

```javascript
let customSlideHTML = `<div class="gslide">
    <div class="gslide-inner-content">
        <div class="ginner-container">
            <div class="gslide-media">
              <div class="gslide-description">
                  <div class="gdesc-inner">
                      <h4 class="gslide-title"></h4>
                      <div class="gslide-desc"></div>
                  </div>
              </div>
            </div>
        </div>
    </div>
</div>`;

let glightbox = GLightbox({
    slideHTML: customSlideHTML,
});
```

CSS:

```css
.glightbox-clean .gslide-description {
    max-width: 100% !important;
}

.glightbox-clean .gdesc-inner {
    -webkit-user-select: auto;
    -moz-user-select: auto;
    -ms-user-select: auto;
    user-select: auto;
}

.glightbox-clean .gdesc-inner a {
    display: inline-block;
}
```

Until I applied the workaround the issue was happening to me with regular jpegs of 1200x800 pixels (2400x1600 size for retina devices) hosted in Amazon S3 with Cloudfront as CDN (home internet speed is 1Gbps).
This is the website were the issue was happening: https://nacho.tokyo/en

The images used in the example site are only like 25KB, and there are only 3. That's way is more difficult to reproduce the issue there unless you throttle the network.
