### ISSUE TITLE
Ability to customize CSS via custom properties

### ISSUE THREAD

**Issue by massimo-cassandro** [biati-digital/glightbox#389]
**Important.**
Before posting a feature request please make sure to search the closed issues, maybe the feature you want to implement has already been asked and denied for not providing a valid explanation or simply because it was something the user wanted for him or his project.

**Please describe the feature you want to be implemented.**
Please note: features should be something that everyone can use and not just something you need for your project.

Introduce the ability to customize some properties of the default css with custom properties

**Explain why the feature is useful**
Describe some usage cases.

It would increase the speed of customization while always keeping the link to the original css and its updates

**Have you seen it somewhere else?**
If so please provide live examples, images, videos, etc. anything that help us understand the feature request

**Additional context**

**Comment by gingerchew** [comment]
Hey there @massimo-cassandro,

I really like this idea! Making theming more accessible with custom props is a great addition. I'm going to add the feature request label so we can be sure to include it in upcoming updates.

**Comment by tomasvn** [comment]
What stuff would you like to see, to be customizable? As basically everything could be moved to css variables, @massimo-cassandro

**Comment by massimo-cassandro** [comment]
I think the more things can be managed by custom variables the more the ability to customize gligthbox will increase: colors. font family, sizes and weight, some dimensions... etc

**Comment by gingerchew** [comment]
Thinking back to this now, here's a general idea of what it could look like (just brainstorming so values aren't real). As far as "decisions" that need to be made, I think these are things to consider:

Prefixing:
```css
.glightbox-container {
  --overlay-color: #fff;
  /** OR */
  --gl-overlay-color: #fff;
}
```
I am definitely in favor of using a prefix (like `--gl-` but can be whatever). I'm using `--gl-` for the rest of the comment though.

Scope: 
```css
:root {
  --gl-image-min-width: 200px;
}
/** OR */
.glightbox-container {
  --gl-image-min-width: 200px; /* declare every variable on the container element */
}
/** OR */
.gslide-image {
  --gl-image-min-width: 200px; /** declare on individual slide type/components
}
```
The second and third [offer some benefits](https://css-tricks.com/breaking-css-custom-properties-out-of-root-might-be-a-good-idea/) maybe the most useful of those being preventing scope creep.

Defaults:
```css
/** Declare each custom property */
.gslide-image {
    --gl-image-min-width: 200px;
    min-width: var(--gl-image-min-width);
}
/** OR */
/** Use the fallback option inside var() */
.gslide-image {
  min-width: var(--gl-image-min-width, 200px);
}
```

Gotta take some time to review the styles and see what can be extracted and what should stay as foundation for each component, but would love insight on the 3 things above.
