### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by oozrafa** [biati-digital/glightbox#66]
Would it be possible to add right-to-left support so that when using the gallery the image will slide in from the left, and the current image will slide out to the right?
It's basically just switching around when the gslideInLeft, gslideInRight, gslideOutLeft and gslideOutRight classes are toggled.

This is the basic idea:
```css
/* RTL next button */
.gnext {
  right: auto !important;
  left: 30px !important; /* change the icon's side */
  transform: scale(-1, 1); /* flip the icon */
}

/* RTL prev button */
.gprev {
  left: auto !important;
  right: 30px !important; /* change the icon's side */
  transform: scale(-1, 1); /* flip the icon */
}

/* reverse all animations for RTL */
.gslideOutLeft {
  -webkit-animation: gslideOutRight .3s ease !important;
  animation: gslideOutRight .3s ease !important;
}

.gslideInLeft {
  -webkit-animation: gslideInRight .3s ease !important;
  animation: gslideInRight .3s ease !important;
}

.gslideOutRight {
  -webkit-animation: gslideOutLeft .3s ease !important;
  animation: gslideOutLeft .3s ease !important;
}

.gslideInRight {
  -webkit-animation: gslideInLeft .3s ease !important;
  animation: gslideInLeft .3s ease !important;
}
```
Not sure if this is the only place in the JS, but the touch events also need to be reversed:
```javascript
swipe: (evt) => {
            if (imageZoomed) {
                return;
            }
            if (doingZoom) {
                doingZoom = false;
                return;
            }
            if (evt.direction == 'Left') {
                if (this.index == this.elements.length - 1) {
                    return resetSlideMove(media)
                }
                this.prevSlide(); // reversed for RTL
            }
            if (evt.direction == 'Right') {
                if (this.index == 0) {
                    return resetSlideMove(media)
                }
                this.nextSlide(); // reversed for RTL
            }
        }
```

Thanks!
